window.STOCK_VIVO = {
 "generado": "2026-07-01 15:51:01",
 "fuente": "admin2 /productos.md?tipos=Grano Verde · stock en vivo",
 "totalSkus": 352,
 "conStock": 120,
 "totalStock": 2418.53,
 "granelKg": 1938,
 "bolsasCount": 481,
 "bolsasKg": 23015,
 "items": [
  {
   "sku": "GRVMOKAESPECIAL",
   "nombre": "Grano Verde Brasil Moka Especial",
   "categoria": "",
   "stock": 319.01,
   "stockSF": 234.37,
   "stockMza": 85.56,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVPERUCHIR",
   "nombre": "Grano Verde Perú Regional Chirinos",
   "categoria": "",
   "stock": 192.83,
   "stockSF": 164.31,
   "stockMza": 28.52,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCSUPREMOHE",
   "nombre": "Grano Verde Colombia Supremo Herrera",
   "categoria": "Cafe verde",
   "stock": 184.43,
   "stockSF": 76.14,
   "stockMza": 108.29,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVBOLIILLAM",
   "nombre": "Grano Verde Bolivia Illampu Ruh",
   "categoria": "",
   "stock": 181.99,
   "stockSF": 194.96,
   "stockMza": -2.85,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONELOCO",
   "nombre": "Grano Verde Honduras El Ocotillo 85",
   "categoria": "",
   "stock": 140.41,
   "stockSF": 97.41,
   "stockMza": 43,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONZANCAT",
   "nombre": "Grano Verde Honduras Zancudero Catuai 87.5",
   "categoria": "",
   "stock": 133.86,
   "stockSF": 54.21,
   "stockMza": 84.34,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLREGIONTOLIM",
   "nombre": "Grano Verde Colombia Regional Tolima Premium",
   "categoria": "",
   "stock": 119.99,
   "stockSF": 88.75,
   "stockMza": 31.24,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCCASTIGAITANATUR",
   "nombre": "Grano Verde Colombia Castillo Gaitana Natural",
   "categoria": "Cafe verde",
   "stock": 87.07,
   "stockSF": 187.36,
   "stockMza": -99,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVBRAREGIOIASELECTION",
   "nombre": "Grano Verde Brasil Ia Selection",
   "categoria": "",
   "stock": 71.27,
   "stockSF": -12.64,
   "stockMza": 85.56,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCCSAND",
   "nombre": "Grano Verde Colombia Coulturing Sandia",
   "categoria": "",
   "stock": 66,
   "stockSF": 66,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCBLENDFIN",
   "nombre": "Grano Verde Colombia Blend Finkap",
   "categoria": "Cafe verde",
   "stock": 56.08,
   "stockSF": 35.44,
   "stockMza": 27.15,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVVIETROBUSR1S16",
   "nombre": "Grano Verde Robusta Vietnam Robusta R1 S16",
   "categoria": "",
   "stock": 55.79,
   "stockSF": 55.79,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONSARCO",
   "nombre": "Grano Verde Honduras El Sarco",
   "categoria": "",
   "stock": 52.68,
   "stockSF": 64.88,
   "stockMza": 0.86,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCAREGIOESPE",
   "nombre": "Bolsa Gv 60kg Brasil Regional Especial",
   "categoria": "Cafe verde",
   "stock": 49,
   "stockSF": 49,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 60
  },
  {
   "sku": "GRVCAREGIOCONTI",
   "nombre": "Bolsa Gv 60kg Brasil Regional Continental",
   "categoria": "Cafe verde",
   "stock": 48,
   "stockSF": 45,
   "stockMza": 3,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 60
  },
  {
   "sku": "GRVCOLBLENDNACI",
   "nombre": "Grano Verde Colombia Blend Nacional",
   "categoria": "",
   "stock": 47.88,
   "stockSF": -10.43,
   "stockMza": 58.95,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVVIETNROBUSTR1S18",
   "nombre": "Grano Verde Robusta Vietnam Robusta R1 S18",
   "categoria": "",
   "stock": 45.6,
   "stockSF": 69.95,
   "stockMza": -24.35,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVBRAREGIOESPECI",
   "nombre": "Grano Verde Brasil Regional Especial",
   "categoria": "",
   "stock": 42.19,
   "stockSF": 42.19,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONLAKEILA",
   "nombre": "Grano Verde Honduras La Keila",
   "categoria": "",
   "stock": 41.05,
   "stockSF": 41.05,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCA023",
   "nombre": "Grano Verde Brasil 023",
   "categoria": "",
   "stock": 40.67,
   "stockSF": 40.67,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVVIETROBUSR2S13",
   "nombre": "Grano Verde Robusta Vietnam Robusta R2 S13",
   "categoria": "",
   "stock": 37.77,
   "stockSF": 37.77,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLCOULTURIFRUTILLAHONEY",
   "nombre": "Grano Verde Colombia Coulturing Frutilla Honey",
   "categoria": "",
   "stock": 37,
   "stockSF": 2.75,
   "stockMza": 34.25,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCUCDFBOLSAPESELV",
   "nombre": "Bolsa Gv 30kg Peru Regional Selva",
   "categoria": "Cafe verde",
   "stock": 36,
   "stockSF": 30,
   "stockMza": 6,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVHONELOCOBOLSA",
   "nombre": "Bolsa Gv 46kg Honduras El Ocotillo 85",
   "categoria": "Cafe verde",
   "stock": 33,
   "stockSF": 33,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCOLPEACHH",
   "nombre": "Grano Verde Colombia Peach Honey",
   "categoria": "",
   "stock": 32.71,
   "stockSF": 14.4,
   "stockMza": 22.54,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLBOURBOROSALAV",
   "nombre": "Grano Verde Colombia Bourbon Rosado Lavado",
   "categoria": "",
   "stock": 30.07,
   "stockSF": -2.35,
   "stockMza": 32.42,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCUCAS",
   "nombre": "Grano Verde Curitiba Moka Caracolillo",
   "categoria": "",
   "stock": 30,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONELNARAN",
   "nombre": "Grano Verde Honduras El Naranjo 84",
   "categoria": "",
   "stock": 29.81,
   "stockSF": 0,
   "stockMza": 32.57,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCAMOKAESPE",
   "nombre": "Bolsa Gv 60kg Brasil Moka Especial",
   "categoria": "Cafe verde",
   "stock": 27,
   "stockSF": 27,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 60
  },
  {
   "sku": "GRVHONLAULTLOT2BOLSA",
   "nombre": "Bolsa Gv 46kg Honduras La Última 85 Lote 2",
   "categoria": "Cafe verde",
   "stock": 24,
   "stockSF": 24,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCCCASTIHON",
   "nombre": "Grano Verde Colombia Castillo Honey",
   "categoria": "",
   "stock": 20.9,
   "stockSF": 18.04,
   "stockMza": 2.86,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLCLASANDIHAR",
   "nombre": "Grano Verde Colombia Clasico Andino Harmony",
   "categoria": "",
   "stock": 20.6,
   "stockSF": -18.08,
   "stockMza": 48.65,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVIMPORTCOFFEEGU",
   "nombre": "Grano Verde Import Coffee Guatemala",
   "categoria": "",
   "stock": 20.1,
   "stockSF": 20.1,
   "stockMza": 0,
   "origen": "",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCHERRYCOL",
   "nombre": "Grano Verde Cherry Seasson Colombia",
   "categoria": "",
   "stock": 20.1,
   "stockSF": 20.1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONLOSLAU",
   "nombre": "Grano Verde Honduras Los Laureles 86.5",
   "categoria": "",
   "stock": 19.01,
   "stockSF": 8.34,
   "stockMza": 21.11,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLXTRE",
   "nombre": "Grano Verde Colombia Bourbon Xtreme",
   "categoria": "",
   "stock": 19,
   "stockSF": 19,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLCOULTURICREMWHIS",
   "nombre": "Grano Verde Colombia Coulturing Crema De Whisky",
   "categoria": "",
   "stock": 19,
   "stockSF": 19,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCCFRYBA",
   "nombre": "Grano Verde Colombia Coulturing Frutilla Y Banana",
   "categoria": "",
   "stock": 18.14,
   "stockSF": 12.87,
   "stockMza": 7.07,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONELOLIBOLSA",
   "nombre": "Bolsa Gv 46kg Honduras Oliva",
   "categoria": "Cafe verde",
   "stock": 18,
   "stockSF": 14,
   "stockMza": 4,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVVIETNROBUSR2S13",
   "nombre": "Bolsa Gv 50kg Vietnam Robusta R2 S13",
   "categoria": "Cafe verde",
   "stock": 17,
   "stockSF": 17,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 50
  },
  {
   "sku": "GRVHONELCEDR",
   "nombre": "Grano Verde Honduras El Cedro 84.5",
   "categoria": "",
   "stock": 16.94,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVVIETNROBUSR1S16",
   "nombre": "Bolsa Gv 50kg Vietnam Robusta R1 S16",
   "categoria": "Cafe verde",
   "stock": 16,
   "stockSF": 16,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 50
  },
  {
   "sku": "GRVHONLATORMEN",
   "nombre": "Bolsa Gv 46kg Honduras La Tormenta",
   "categoria": "Cafe verde",
   "stock": 15,
   "stockSF": 15,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCCASTIGAITALAV",
   "nombre": "Bolsa Gv 70kg Colombia Gaitana Lavado",
   "categoria": "Cafe verde",
   "stock": 13.6,
   "stockSF": 13,
   "stockMza": 3,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 70
  },
  {
   "sku": "GRVHONLAULT",
   "nombre": "Grano Verde Honduras La Última 85",
   "categoria": "",
   "stock": 13.07,
   "stockSF": 0,
   "stockMza": 15.46,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCSUPREMHERR",
   "nombre": "Bolsa Gv 70kg Colombia Supremo Herrera",
   "categoria": "Cafe verde",
   "stock": 13,
   "stockSF": 12,
   "stockMza": 1,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 70
  },
  {
   "sku": "GRVCUCDFBOLSABOLILLAMPUTREI",
   "nombre": "Bolsa Gv 30kg Bolivia Illampú",
   "categoria": "Cafe verde",
   "stock": 12,
   "stockSF": 8,
   "stockMza": 4,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCLAVAGEISHASANAN",
   "nombre": "Bolsa Gv 35kg Colombia Lavado Geisha San Antonio",
   "categoria": "Cafe verde",
   "stock": 12,
   "stockSF": 12,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 35
  },
  {
   "sku": "GRVVIETNROBUSR1S18CLEAN",
   "nombre": "Bolsa Gv 50kg Vietnam Robusta R1 S18 Clean",
   "categoria": "Cafe verde",
   "stock": 11,
   "stockSF": 9,
   "stockMza": 2,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 50
  },
  {
   "sku": "GRVHONBENITO",
   "nombre": "Bolsa Gv 46kg Honduras Benito",
   "categoria": "Cafe verde",
   "stock": 11,
   "stockSF": 11,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVVIETNROBUSR1S18",
   "nombre": "Bolsa Gv 50kg Vietnam Robusta R1 S18",
   "categoria": "Cafe verde",
   "stock": 10,
   "stockSF": 10,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 50
  },
  {
   "sku": "GRVCUCDFBOLSAPELUZMARIT",
   "nombre": "Bolsa Gv 30kg Peru Regional Luz Maritsa",
   "categoria": "Cafe verde",
   "stock": 10,
   "stockSF": 10,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCUCDFBOLSAMARITEREVIDA",
   "nombre": "Bolsa Gv 30kg Peru Regional Maria Teresa Vidarte",
   "categoria": "Cafe verde",
   "stock": 10,
   "stockSF": 10,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVBRAREGIOCONTINEN",
   "nombre": "Grano Verde Brasil Regional Continental",
   "categoria": "",
   "stock": 8.46,
   "stockSF": 37.12,
   "stockMza": -28.66,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONLASARCO",
   "nombre": "Bolsa Gv 46kg Honduras El Sarco",
   "categoria": "Cafe verde",
   "stock": 8,
   "stockSF": 4,
   "stockMza": 4,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCUCDFBOLSAPERUFAELI",
   "nombre": "Bolsa Gv 30kg Peru Regional Rufasto Elias",
   "categoria": "Cafe verde",
   "stock": 8,
   "stockSF": 8,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCUCDFBOLSAPEJULRUIZGAR",
   "nombre": "Bolsa Gv 30kg Peru Regional Julia Ruiz De Garcia",
   "categoria": "Cafe verde",
   "stock": 8,
   "stockSF": 8,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCUCDFBOLSAPEFLOROCANA",
   "nombre": "Bolsa Gv 30kg Peru Regional Florentino Ocaña",
   "categoria": "Cafe verde",
   "stock": 8,
   "stockSF": 8,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVHONDOSHERMANOS",
   "nombre": "Bolsa Gv 46kg Honduras Dos Hermanos",
   "categoria": "Cafe verde",
   "stock": 7,
   "stockSF": 7,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCUCDFBOLSABOLILLAMPUSES",
   "nombre": "Bolsa Gv 60kg Bolivia Illampú",
   "categoria": "Cafe verde",
   "stock": 7,
   "stockSF": 5,
   "stockMza": 2,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 60
  },
  {
   "sku": "GRVCCMAN",
   "nombre": "Grano Verde Colombia Coulturing Mango",
   "categoria": "",
   "stock": 6.47,
   "stockSF": 6.47,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCBLENDFINKAP",
   "nombre": "Bolsa Gv 70kg Colombia Blend Finkap",
   "categoria": "Cafe verde",
   "stock": 6,
   "stockSF": 5,
   "stockMza": 1,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 70
  },
  {
   "sku": "GRVCA005",
   "nombre": "Grano Verde Brasil 005",
   "categoria": "",
   "stock": 5.71,
   "stockSF": 0.04,
   "stockMza": 11.65,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONLOSOCO",
   "nombre": "Grano Verde Honduras Los Ocotes 82.5",
   "categoria": "",
   "stock": 5.47,
   "stockSF": 6.56,
   "stockMza": 2,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONBAMBU",
   "nombre": "Bolsa Gv 46kg Honduras Bambu",
   "categoria": "Cafe verde",
   "stock": 5,
   "stockSF": 5,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCAPERUMARIOJESUSRB39",
   "nombre": "Bolsa Gv 30kg Peru Mario Jesus Rb39",
   "categoria": "Cafe verde",
   "stock": 5,
   "stockSF": 3,
   "stockMza": 2,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCAPERUMARIOJESUS",
   "nombre": "Bolsa Gv 30kg Peru Mario Jesus Altura",
   "categoria": "Cafe verde",
   "stock": 5,
   "stockSF": 3,
   "stockMza": 2,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCAPERUMARAGOGIPE",
   "nombre": "Bolsa Gv 30kg Peru Maragogipe",
   "categoria": "Cafe verde",
   "stock": 5,
   "stockSF": 3,
   "stockMza": 2,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVHONLASPENAS",
   "nombre": "Grano Verde Honduras Las Peñas",
   "categoria": "",
   "stock": 4.38,
   "stockSF": 0,
   "stockMza": 4.38,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVIMPORTETIO",
   "nombre": "Grano Verde Import Coffee Etiopia",
   "categoria": "",
   "stock": 4.32,
   "stockSF": 4.32,
   "stockMza": 0,
   "origen": "",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONCOPROCAEL",
   "nombre": "Bolsa Gv 46kg Honduras Coprocael",
   "categoria": "Cafe verde",
   "stock": 4,
   "stockSF": 4,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCOLTYPIHONEY",
   "nombre": "Grano Verde Colombia Typica Honey",
   "categoria": "",
   "stock": 3.46,
   "stockSF": 3.46,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONCASCADAS",
   "nombre": "Bolsa Gv 46kg Honduras Cascadas",
   "categoria": "Cafe verde",
   "stock": 3,
   "stockSF": 3,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCBOURBONXTRE",
   "nombre": "Bolsa Gv 35kg Colombia Bourbon Xtreme",
   "categoria": "Cafe verde",
   "stock": 3,
   "stockSF": 3,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 35
  },
  {
   "sku": "GRVCAPERMARINAGEI",
   "nombre": "Bolsa Gv 30kg Peru Marina Geisha",
   "categoria": "Cafe verde",
   "stock": 3,
   "stockSF": 3,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCHERRYPER",
   "nombre": "Grano Verde Cherry Seasson Peru",
   "categoria": "",
   "stock": 2.56,
   "stockSF": 2.56,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONPIEHERRLOTE2",
   "nombre": "Grano Verde Honduras Piedra Herrada 83 Lote 2",
   "categoria": "",
   "stock": 1.92,
   "stockSF": 1.92,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONZANPARAI",
   "nombre": "Grano Verde Honduras Zancudero Parainema 85",
   "categoria": "",
   "stock": 1.68,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLEXCELSOLALOMA",
   "nombre": "Grano Verde Colombia Excelso La Loma",
   "categoria": "",
   "stock": 1.44,
   "stockSF": 1.44,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLEXCELSOBLEND",
   "nombre": "Grano Verde Colombia Excelso Blend Del Sur",
   "categoria": "",
   "stock": 1.05,
   "stockSF": 1.05,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONLOSLAUBOLSA",
   "nombre": "Bolsa Gv 46kg Honduras Los Laureles 86.5",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 0,
   "stockMza": 1,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVHONLATRANQUILOT9",
   "nombre": "Bolsa Gv 46kg Honduras La Tranquila",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVHONLASPENPACA",
   "nombre": "Bolsa Gv 46kg Honduras Las Peñas Pacamara",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVHONLASPENLOT10",
   "nombre": "Bolsa Gv 46kg Honduras Las Peñas Lote 10",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 0,
   "stockMza": 1,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVHONELNARANJO",
   "nombre": "Bolsa Gv 46kg Honduras El Naranjo 84",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 0,
   "stockMza": 1,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 46
  },
  {
   "sku": "GRVCPEACHHONEYCAJA",
   "nombre": "Caja Gv 24kg Colombia Peach Honey",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLBOURBROSA",
   "nombre": "Bolsa Gv 35kg Colombia Bourbon Rosado Honey",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 35
  },
  {
   "sku": "GRVCJAVALAROCH",
   "nombre": "Bolsa Gv 70kg Colombia Java La Rochela",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 70
  },
  {
   "sku": "GRVCGEISHALAVTO",
   "nombre": "Bolsa Gv 35kg Colombia Geisha Lavado",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 35
  },
  {
   "sku": "GRVCABOMJESUSFER",
   "nombre": "Bolsa Gv 30kg Brasil Bom Jesus Fermentado",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 30
  },
  {
   "sku": "GRVCA005BOLSA",
   "nombre": "Bolsa Gv 60kg Brasil 005",
   "categoria": "Cafe verde",
   "stock": 1,
   "stockSF": 1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 60
  },
  {
   "sku": "GRVCOLBOURROHOTO",
   "nombre": "Grano Verde Colombia Bourbon Rosado Honey Tolima",
   "categoria": "",
   "stock": 0.9,
   "stockSF": -0.1,
   "stockMza": 1,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVIMPORTCOFFEBR",
   "nombre": "Grano Verde Import Coffee Brasil",
   "categoria": "",
   "stock": 0.69,
   "stockSF": 0.69,
   "stockMza": 0,
   "origen": "",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHON82",
   "nombre": "Grano Verde Honduras Chavelo Parainema 82",
   "categoria": "",
   "stock": 0.2,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVIMPCOL",
   "nombre": "Grano Verde Import Colombia",
   "categoria": "",
   "stock": 0.18,
   "stockSF": 0.18,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCA008",
   "nombre": "Grano Verde Brasil 008",
   "categoria": "",
   "stock": 0.1,
   "stockSF": 0.1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCCLYCH",
   "nombre": "Grano Verde Colombia Coulturing Lyche",
   "categoria": "",
   "stock": 0.05,
   "stockSF": 3.17,
   "stockMza": 0.48,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCA002",
   "nombre": "Grano Verde Brasil 002",
   "categoria": "",
   "stock": 0.01,
   "stockSF": 0.01,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCGEISHAHONEYTO",
   "nombre": "Bolsa Gv 35kg Colombia Geisha Honey Tolima",
   "categoria": "Cafe verde",
   "stock": 0,
   "stockSF": -1,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "bolsa",
   "bolsaKg": 35
  },
  {
   "sku": "GRVCUDES",
   "nombre": "Grano Verde Curitiba Colombia Descafeinado",
   "categoria": "",
   "stock": -0.06,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONLASPENASGEISHA",
   "nombre": "Grano Verde Honduras Las Peñas Geisha",
   "categoria": "",
   "stock": -1,
   "stockSF": 0,
   "stockMza": -1,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GVCMAL08",
   "nombre": "Grano Verde Campos Altos 08",
   "categoria": "",
   "stock": -1.64,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLPLANDTOLIMA",
   "nombre": "Grano Verde Colombia Planadas Tolima",
   "categoria": "",
   "stock": -1.96,
   "stockSF": -1.96,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCAROB106",
   "nombre": "Grano Verde Campos Altos Robusta 106",
   "categoria": "",
   "stock": -2.19,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLBUESACO",
   "nombre": "Grano Verde Colombia Buesaco",
   "categoria": "",
   "stock": -2.29,
   "stockSF": -2.29,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONSOCIOSCATU",
   "nombre": "Grano Verde Honduras Los Socios Catuai",
   "categoria": "Cafe verde",
   "stock": -2.94,
   "stockSF": 42.06,
   "stockMza": -45,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONBRISAS",
   "nombre": "Grano Verde Honduras Brisas",
   "categoria": "",
   "stock": -3,
   "stockSF": -3,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONPIEHERR",
   "nombre": "Grano Verde Honduras Piedra Herrada 85",
   "categoria": "",
   "stock": -3.1,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "B2B",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLCOULTURMARACUHONE",
   "nombre": "Grano Verde Colombia Coulturing Maracuya Honey",
   "categoria": "",
   "stock": -6,
   "stockSF": -6,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLCATURRAHONEY",
   "nombre": "Grano Verde Colombia Caturra Honey",
   "categoria": "",
   "stock": -7.28,
   "stockSF": -7.28,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCOLGEISHALAVADO",
   "nombre": "Grano Verde Colombia Geisha Lavado",
   "categoria": "",
   "stock": -9.6,
   "stockSF": -17.7,
   "stockMza": 8.1,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONCHAV2",
   "nombre": "Grano Verde Honduras Chavelo 2 88.5",
   "categoria": "",
   "stock": -11.8,
   "stockSF": -11.8,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GVKENAAMA",
   "nombre": "Grano Verde Kenia Aa Masai",
   "categoria": "",
   "stock": -13,
   "stockSF": -13,
   "stockMza": 0,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCUMXO",
   "nombre": "Grano Verde Curitiba Mexico Organico",
   "categoria": "",
   "stock": -14,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCUNLB",
   "nombre": "Grano Verde Curitiba Nicaragua Finca La Bendicion",
   "categoria": "",
   "stock": -19.91,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GVCUPERU",
   "nombre": "Grano Verde Curitiba Peru Finca Los Santos",
   "categoria": "",
   "stock": -35,
   "stockSF": 0,
   "stockMza": 0,
   "origen": "",
   "activo": false,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCAZAFPRIMITIV",
   "nombre": "Grano Verde Colombia Azafran Primitivo",
   "categoria": "Cafe verde",
   "stock": -43.3,
   "stockSF": -43,
   "stockMza": -0.3,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVHONDUOLIVA",
   "nombre": "Grano Verde Honduras Oliva",
   "categoria": "",
   "stock": -54.19,
   "stockSF": -30.19,
   "stockMza": -24,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVCUVIETNROBUSTR1S18CL",
   "nombre": "Grano Verde Robusta Vietnam Robusta R1 S18 Clean",
   "categoria": "",
   "stock": -61.63,
   "stockSF": -143.63,
   "stockMza": 82,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  },
  {
   "sku": "GRVBOMJESUS",
   "nombre": "Grano Verde Brasil Bom Jesus Fermentado",
   "categoria": "Cafe verde",
   "stock": -81.25,
   "stockSF": -10.78,
   "stockMza": -70.47,
   "origen": "B2B",
   "activo": true,
   "clase": "granel",
   "bolsaKg": 0
  }
 ]
};
